//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMoviesReviews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmovi()
        {
            this.GlumljenjeFilma = new HashSet<GlumljenjeFilma>();
            this.RecenzijeFilmova = new HashSet<RecenzijeFilmova>();
        }
    
        public int Id { get; set; }
        public string Naslov { get; set; }
        public byte[] Slika { get; set; }
        public string Opis { get; set; }
        public System.DateTime DatumRealizacije { get; set; }
        public Nullable<int> KategorijaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlumljenjeFilma> GlumljenjeFilma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecenzijeFilmova> RecenzijeFilmova { get; set; }
        public virtual KategorijaFilma KategorijaFilma { get; set; }
    }
}
