//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMoviesReviews.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eMovies2019Entities : DbContext
    {
        public eMovies2019Entities()
            : base("name=eMovies2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filmovi> Filmovi { get; set; }
        public virtual DbSet<Glumci> Glumci { get; set; }
        public virtual DbSet<GlumljenjeFilma> GlumljenjeFilma { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<RecenzijeFilmova> RecenzijeFilmova { get; set; }
        public virtual DbSet<KategorijaFilma> KategorijaFilma { get; set; }
    
        public virtual ObjectResult<esp_SelectFromUsers_Result> esp_SelectFromUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SelectFromUsers_Result>("esp_SelectFromUsers");
        }
    
        public virtual ObjectResult<esp_GetTop10RatedMovies_Result> esp_GetTop10RatedMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_GetTop10RatedMovies_Result>("esp_GetTop10RatedMovies");
        }
    
        public virtual ObjectResult<esp_GetTop10RatedMovies_Result> esp_GetTop10RatedTVshows(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_GetTop10RatedMovies_Result>("esp_GetTop10RatedTVshows", param1Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovie(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovie", param1Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieBetweenMinAndExact(Nullable<double> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieBetweenMinAndExact", param1Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByEarlierDate(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByEarlierDate", param1Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByExactRating(Nullable<double> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByExactRating", param1Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByLaterDate(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByLaterDate", param1Parameter);
        }
    
        public virtual ObjectResult<esp_GetTop10RatedMovies_Result> esp_LoadTenMoreMoviesResults(Nullable<double> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_GetTop10RatedMovies_Result>("esp_LoadTenMoreMoviesResults", param1Parameter);
        }
    
        public virtual ObjectResult<esp_GetTop10RatedMovies_Result> esp_LoadTenMoreTvShowsResults(Nullable<double> param1, string param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            var param2Parameter = param2 != null ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_GetTop10RatedMovies_Result>("esp_LoadTenMoreTvShowsResults", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_GetAllMovies_Result> esp_GetAllMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_GetAllMovies_Result>("esp_GetAllMovies");
        }
    
        public virtual int esp_AddRatingToMovie(Nullable<int> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_AddRatingToMovie", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieSkip10Rows(string param1, Nullable<int> param2)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieSkip10Rows", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieBetweenMinAndExactSkip10Rows(Nullable<double> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieBetweenMinAndExactSkip10Rows", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByEarlierDateSkip10Rows(Nullable<int> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByEarlierDateSkip10Rows", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByExactRatingSkip10Rows(Nullable<double> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(double));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByExactRatingSkip10Rows", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<esp_SearchMovie_Result> esp_SearchMovieByLaterDateSkip10Rows(Nullable<int> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_SearchMovie_Result>("esp_SearchMovieByLaterDateSkip10Rows", param1Parameter, param2Parameter);
        }
    }
}
